# Generated by Django 5.1.4 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
