# Generated by Django 5.2 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_image_url_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(
                choices=[
                    ('Beginner', 'Beginner'),
                    ('Intermediate', 'Intermediate'),
                    ('Advanced', 'Advanced'),
                ],
                default='Beginner',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(
                choices=[
                    ('2 Weeks', '2 Weeks'),
                    ('4 Weeks', '4 Weeks'),
                    ('6 Weeks', '6 Weeks'),
                    ('8 Weeks', '8 Weeks'),
                    ('12 Weeks', '12 Weeks'),
                ],
                default='6 Weeks',
                max_length=20,
            ),
        ),
    ]
