# Generated by Django 5.2 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_duration_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
    ]
