# Generated by Django 5.2 on 2026-07-22

import uuid

from django.db import migrations, models
import django.db.models.deletion


def create_certificates_for_completed_enrollments(apps, schema_editor):
    """Make already completed, eligible enrollments downloadable after upgrade."""
    Enrollment = apps.get_model('courses', 'Enrollment')
    Certificate = apps.get_model('courses', 'Certificate')
    Payment = apps.get_model('courses', 'Payment')

    for enrollment in Enrollment.objects.filter(completed=True).select_related('course'):
        if enrollment.course.price > 0 and not Payment.objects.filter(
            student_id=enrollment.student_id,
            course_id=enrollment.course_id,
            paid=True,
        ).exists():
            continue
        Certificate.objects.get_or_create(enrollment_id=enrollment.id)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_external_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment')),
            ],
        ),
        migrations.RunPython(create_certificates_for_completed_enrollments, migrations.RunPython.noop),
    ]
